import type { Employee } from './types'

export const seedEmployees: Employee[] = [
  {
    id: '1',
    employeeCode: 'EMP001',
    firstName: 'Aarav',
    lastName: 'Sharma',
    email: 'aarav.sharma@company.com',
    phone: '+91 98765 43210',
    department: 'Engineering',
    designation: 'Senior Developer',
    joiningDate: '2022-03-15',
    salary: 1200000,
    status: 'Active',
  },
  {
    id: '2',
    employeeCode: 'EMP002',
    firstName: 'Priya',
    lastName: 'Patel',
    email: 'priya.patel@company.com',
    phone: '+91 98765 43211',
    department: 'Human Resources',
    designation: 'HR Manager',
    joiningDate: '2021-07-01',
    salary: 950000,
    status: 'Active',
  },
  {
    id: '3',
    employeeCode: 'EMP003',
    firstName: 'Rohan',
    lastName: 'Mehta',
    email: 'rohan.mehta@company.com',
    phone: '+91 98765 43212',
    department: 'Finance',
    designation: 'Accountant',
    joiningDate: '2023-01-10',
    salary: 720000,
    status: 'Active',
  },
  {
    id: '4',
    employeeCode: 'EMP004',
    firstName: 'Sneha',
    lastName: 'Kapoor',
    email: 'sneha.kapoor@company.com',
    phone: '+91 98765 43213',
    department: 'Marketing',
    designation: 'Marketing Lead',
    joiningDate: '2020-11-20',
    salary: 1100000,
    status: 'Inactive',
  },
  {
    id: '5',
    employeeCode: 'EMP005',
    firstName: 'Vikram',
    lastName: 'Singh',
    email: 'vikram.singh@company.com',
    phone: '+91 98765 43214',
    department: 'Engineering',
    designation: 'QA Engineer',
    joiningDate: '2023-06-05',
    salary: 850000,
    status: 'Active',
  },
  {
    id: '6',
    employeeCode: 'EMP006',
    firstName: 'Ananya',
    lastName: 'Reddy',
    email: 'ananya.reddy@company.com',
    phone: '+91 98765 43215',
    department: 'Sales',
    designation: 'Sales Executive',
    joiningDate: '2024-02-12',
    salary: 650000,
    status: 'Active',
  },
  {
    id: '7',
    employeeCode: 'EMP007',
    firstName: 'Kabir',
    lastName: 'Nair',
    email: 'kabir.nair@company.com',
    phone: '+91 98765 43216',
    department: 'Engineering',
    designation: 'DevOps Engineer',
    joiningDate: '2022-09-18',
    salary: 1050000,
    status: 'Active',
  },
  {
    id: '8',
    employeeCode: 'EMP008',
    firstName: 'Meera',
    lastName: 'Iyer',
    email: 'meera.iyer@company.com',
    phone: '+91 98765 43217',
    department: 'Operations',
    designation: 'Operations Manager',
    joiningDate: '2019-05-22',
    salary: 1300000,
    status: 'Inactive',
  },
  {
    id: '9',
    employeeCode: 'EMP009',
    firstName: 'Arjun',
    lastName: 'Desai',
    email: 'arjun.desai@company.com',
    phone: '+91 98765 43218',
    department: 'Engineering',
    designation: 'Frontend Developer',
    joiningDate: '2024-08-01',
    salary: 780000,
    status: 'Active',
  },
  {
    id: '10',
    employeeCode: 'EMP010',
    firstName: 'Diya',
    lastName: 'Malhotra',
    email: 'diya.malhotra@company.com',
    phone: '+91 98765 43219',
    department: 'Design',
    designation: 'UI/UX Designer',
    joiningDate: '2023-04-14',
    salary: 900000,
    status: 'Active',
  },
  {
    id: '11',
    employeeCode: 'EMP011',
    firstName: 'Ishaan',
    lastName: 'Joshi',
    email: 'ishaan.joshi@company.com',
    phone: '+91 98765 43220',
    department: 'Finance',
    designation: 'Financial Analyst',
    joiningDate: '2021-12-03',
    salary: 880000,
    status: 'Active',
  },
  {
    id: '12',
    employeeCode: 'EMP012',
    firstName: 'Tara',
    lastName: 'Bhatia',
    email: 'tara.bhatia@company.com',
    phone: '+91 98765 43221',
    department: 'Human Resources',
    designation: 'Recruiter',
    joiningDate: '2024-01-08',
    salary: 600000,
    status: 'Inactive',
  },
]
